added node.js; controlling and texturing were umproved
EpicLegend/minecraft pull request #1
Opened 2021-02-10 16:23 UTC by russian-proger

Настроил текстуры, добавил возможность передвижения вверх-вниз. Запуск осуществляется через сервер по ссылке http://localhost;80/

2021-02-10 16:34 UTC, russian-proger commented
Можно создать вполне реальный клон майнкрафта, у меня есть несколько идей по дальнейшему развитию этого проекта

2021-02-10 16:36 UTC, russian-proger commented
Хранение блоков можно осуществить при помощи IDB (Indexed Database) - единственный вариант, который нашёл

2021-02-10 16:38 UTC, russian-proger commented
Обычный Geometry от либы THREE не подойдёт - надо юзать BufferGeometry

2021-02-10 16:38 UTC, russian-proger commented
А также в качестве текстур можно применить тайлы

2021-02-10 22:11 UTC, EpicLegend commented
Использовать 15v node как то плохо... 
я так считаю.

2021-02-10 22:21 UTC, EpicLegend commented
Посмотрел игру.
Я думал, ты добавил гравитацию(когда говорил про передвижение вверх-вниз. ) =)
Прикольно получилось. Огонь!
Я хочу переделать это.
Хочется сделать демку первой версии игры(самой первой).
На данный момент я не знаю как оптимизировать все это т.к. даже в 1000 блоков уже лаги ужасные.
Да и займусь этим лишь в марте т.к. сейчас другие дела есть.
Если хочешь, то я могу написать когда буду это делать и можем вместе создать этот проект.

2021-02-10 22:27 UTC, EpicLegend requested changes
refactoring

2021-02-10 22:28 UTC, merged

2021-02-11 09:13 UTC, russian-proger commented
Есть способы, как всё оптимизировать:
1. Вместо Geometry использовать BufferGeometry. Хранить все регионы/чанки/блоки надо в одной геометрии. То есть это будет один объект в сцене и это будет работать быстрее за счёт того, что все вычисления с блоками будет обрабатывать не THREE.js, а наш кастомный скрипт.

2. Использовать WebAssembler. Можно написать код на C или C++, и подключить скомпилированный в .wasm код к странице.

3. Освещение надо делать кастомную, такую, чтобы можно было кэшировать.

2021-02-11 09:14 UTC, russian-proger commented
Напиши когда будешь начинать делать, я с радостью помогу

2021-02-28 12:31 UTC, EpicLegend commented
Привет.
У меня появилось время. Я готов начать разработку нормальной версии minecraft.
Дай мне свои контакты(vk, telegram или что-то подобное)

2021-02-28 14:57 UTC, russian-proger commented
Привет

2021-02-28 14:58 UTC, russian-proger commented
VK: https://vk.com/russian_proger